name: Run Ngspice Simulations

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ngspice and gnuplot
        run: |
          sudo apt-get update
          sudo apt-get install -y ngspice gnuplot

      # --- Attenuator ---
      - name: Simulate Attenuator
        run: |
          cd attenuator
          ngspice -b attenuator.cir
          gnuplot -e "set terminal png; \
            set output 'attenuator.png'; \
            plot 'attenuator.raw' using 1:2 with lines title 'IN', \
                 'attenuator.raw' using 1:3 with lines title 'OUT';"
          mkdir -p output
          mv attenuator.png output/

      # --- Half Wave Rectifier ---
      - name: Simulate Rectifier
        run: |
          cd half-wave-rectifier
          ngspice -b rectifier.cir
          gnuplot -e "set terminal png; \
            set output 'rectifier.png'; \
            plot 'rectifier.raw' using 1:2 with lines title 'IN', \
                 'rectifier.raw' using 1:3 with lines title 'OUT';"
          mkdir -p output
          mv rectifier.png output/

      - name: Commit Results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update simulation results" || echo "No changes"
          git push || true
